let rol_def_tests = 
//Array de arrays
Array(
    //Esquema de arrays para definicion de tests...
   Array('rol','id_rol','input',1,'Validar min_size de id_rol en EDIT (min 1)','EDIT','id_rol_min_size_KO','Id de rol vacio, introduzca un id en EDIT'),
   Array('rol','id_rol','input',2,'Validar max_size de id_rol en EDIT (max 11)','EDIT','id_rol_max_size_KO','Id de rol demasiado es largo, introduzca maximo 11 digitos en EDIT'),
   Array('rol','id_rol','input',3,'Validar el format de id_role en Edit','EDIT','id_rol_format_KO','Id de rol debe ser numerico en EDIT'),
   Array('rol','id_rol','input',4,'Validar id rol corrcto en EDIT','EDIT',true,'Id de rol correcto en EDIT'),
   Array('rol','rol_name','input',5,'Validar min_size de rol_name en ADD (min 5)','ADD','rol_name_min_size_KO','Nombre de rol demasiado corto, minimo 5 caracteres'),
   Array('rol','rol_name','input',6,'Validar max_size de rol_name en ADD (max 48)','ADD','rol_name_max_size_KO','Nombre de rol demasiado largo, maximo 48 caracteres'),
   Array('rol','rol_name','input',7,'Validar el format de rol_name en ADD','ADD','rol_name_format_KO','Nombre de rol solo admite letras'),
   Array('rol','rol_name','input',8,'Validar rol_name correcto en ADD','ADD',true,'Nombre de rol correcto'),
   Array('rol','rol_name','input',9,'Validar min_size de rol_name en EDIT (min 5)','EDIT','rol_name_min_size_KO','Nombre de rol demasiado corto, minimo 5 caracteres en EDIT'),
   Array('rol','rol_name','input',10,'Validar max_size de rol_name en EDIT (max 48)','EDIT','rol_name_max_size_KO','Nombre de rol demasiado largo, maximo 48 caracteres en EDIT'),
   Array('rol','rol_name','input',11,'Validar format de rol_name en EDIT','EDIT','rol_name_format_KO','Nombre de rol solo admite letras en EDIT'),
   Array('rol','rol_name','input',12,'Validar rol_name correcto en EDIT','EDIT',true ,'Nombre de rol correcto en EDIT'),
   Array('rol','rol_description','input',13,'Validar min_size de rol_description en ADD (min 5)','ADD','rol_description_min_size_KO','Descripcion demasiado corta, minimo 5 caracteres'),
   Array('rol','rol_description','input',14,'Validar max_size de rol_description en ADD (max 200)','ADD','rol_description_max_size_KO','Descripcion demasiado larga, maximo 48 caracteres'),
   Array('rol','rol_description','input',15,'Validar format de rol_description en ADD','ADD','rol_description_format_KO','no puedes escribir caracteres en la description'),
   Array('rol','rol_description','input',16,'Validar rol_description correcto en ADD','ADD',true,'Descripcion del rol es correcto'),
   Array('rol','rol_description','input',17,'Validar min_size de rol_description en EDIT (min 5)','EDIT','rol_description_min_size_KO','Descripcion demasiado corta, minimo 5 caracteres'),
   Array('rol','rol_description','input',18,'Validar max_size de rol_description en EDIT (max 200)','EDIT','rol_description_max_size_KO','Descripcion demasiado larga, maximo 48 caracteres'),
   Array('rol','rol_description','input',19,'Validar format de rol_description en EDIT','EDIT','rol_description_format_KO','no puedes escribir caracteres en la description'),
   Array('rol','rol_description','input',20,'Validar rol_description correcto en EDIT','EDIT',true,'Descripcion del rol es correcto'),
   


);

//Definicion de pruebas que usen los tests creados anteriormente
let rol_pruebas = 
Array(
    //Esquema de arrays para la definicion de pruebas...
    Array('rol','id_rol',1,1,'EDIT',{id_rol:''},'id_rol_min_size_KO'),
    Array('rol','id_rol',1,2,'EDIT',{id_rol:'1'},true),
    Array('rol','id_rol',2,3,'EDIT',{id_rol:'123456789012'},'id_rol_max_size_KO'),
    Array('rol','id_rol',2,4,'EDIT',{id_rol:'12345678901'},true),
    Array('rol','id_rol',3,5,'EDIT',{id_rol:'12a'},'id_rol_format_KO'),
    Array('rol','id_rol',3,6,'EDIT',{id_rol:'-5'},'id_rol_format_KO'),
    Array('rol','id_rol',3,7,'EDIT',{id_rol:'1.5'},'id_rol_format_KO'),
    Array('rol','id_rol',4,8,'EDIT',{id_rol:'1'},true),
    Array('rol','id_rol',4,9,'EDIT',{id_rol:'123'},true),
    array('rol','rol_name',5,10,'ADD',{rol_name:''},'rol_name_min_size_KO'),
    array('rol','rol_name',5,11,'ADD',{rol_name:'abcd'},'rol_name_min_size_KO'),
    array('rol','rol_name',5,12,'ADD',{rol_name:'abcde'},true),
    array('rol','rol_name',6,13,'ADD',{rol_name:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'},'rol_name_max_size_KO'),
    array('rol','rol_name',6,14,'ADD',{rol_name:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'},true),
    array('rol','rol_name',7,15,'ADD',{rol_name:'admin67'},'rol_name_format_KO'),
    array('rol','rol_name',7,16,'ADD',{rol_name:'rol@amdin'},'rol_name_format_KO'),
    array('rol','rol_name',7,17,'ADD',{rol_name:'rol_amdin'},'rol_name_format_KO'),
    array('rol','rol_name',8,18,'ADD',{rol-name:'admin'},true),
    array('rol','rol_name',8,19,'ADD',{rol-name:'alumno'},true),
    array('rol','rol_name',8,20,'ADD',{rol-name:'profesor'},true),
    array('rol','rol_name',9,21,'EDIT',{rol-name:'abcd'},'rol_name_min_size_KO'),
    array('rol','rol_name',9,22,'EDIT',{rol-name:''},'rol_name_min_size_KO'),
    array('rol','rol_name',9,23,'EDIT',{rol-name:'abcde'},true),
    array('rol','rol_name',10,24,'EDIT',{rol_name:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'},'rol_name_max_size_KO'),
    array('rol','rol_name',10,25,'EDIT',{rol_name:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'},true),
    array('rol','rol_name',11,26,'ADD',{rol_name:'admin67'},'rol_name_format_KO'),
    array('rol','rol_name',11,27,'ADD',{rol_name:'rol@amdin'},'rol_name_format_KO'),
    array('rol','rol_name',11,28,'ADD',{rol_name:'rol_amdin'},'rol_name_format_KO'),
    array('rol','rol_name',12,29,'ADD',{rol-name:'admin'},true),
    array('rol','rol_name',12,30,'ADD',{rol-name:'alumno'},true),
    array('rol','rol_name',12,31,'ADD',{rol-name:'profesor'},true),
    array('rol','rol_description',13,32,'ADD',{rol_name:''},'rol_name_min_size_KO'),
    array('rol','rol_description',13,33,'ADD',{rol_name:'abcd'},'rol_name_min_size_KO'),
    array('rol','rol_description',13,34,'ADD',{rol_name:'abcde'},true),
    Array('rol','rol_description',14,35,'ADD',{rol_description:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'},'rol_description_max_size_KO'),
    Array('rol','rol_description',14,36,'ADD',{rol_description:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'},true),
    Array('rol','rol_description',15,37,'ADD',{rol_description:'Descripcion @ 123'},'rol_description_format_KO'),
    Array('rol','rol_description',15,38,'ADD',{rol_description:'Descripcion#123'},'rol_description_format_KO'),
    Array('rol','rol_description',16,39,'ADD',{rol_description:'Descripcion-123 España'},true),
    array('rol','rol_description',13,32,'EDIT',{rol_name:''},'rol_name_min_size_KO'),
    array('rol','rol_description',13,33,'EDIT',{rol_name:'abcd'},'rol_name_min_size_KO'),
    array('rol','rol_description',13,34,'EDIT',{rol_name:'abcde'},true),
    Array('rol','rol_description',14,35,'EDIT',{rol_description:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'},'rol_description_max_size_KO'),
    Array('rol','rol_description',14,36,'EDIT',{rol_description:'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'},true),
    Array('rol','rol_description',15,37,'EDIT',{rol_description:'Descripcion @ 123'},'rol_description_format_KO'),
    Array('rol','rol_description',15,38,'EDIT',{rol_description:'Descripcion#123'},'rol_description_format_KO'),
    Array('rol','rol_description',16,39,'EDIT',{rol_description:'Descripcion-123 España'},true),

);
